Workshop8/travel/models.py
from . import db
from datetime import datetime

class User(db.Model):
    __tablename__='users' # good practice to specify table name
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), index=True, unique=True, nullable=False)
    emailid = db.Column(db.String(100), index=True, nullable=False)
	#password is never stored in the DB, an encrypted password is stored
	# the storage should be at least 255 chars long
    password_hash = db.Column(db.String(255), nullable=False)

    # relation to call user.comments and comment.created_by
    comments = db.relationship('Comment', backref='user')



class Destination(db.Model):
    __tablename__ = 'destinations'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    description = db.Column(db.String(200))
    image = db.Column(db.String(400))
    currency = db.Column(db.String(3))
    # ... Create the Comments db.relationship
	# relation to call destination.comments and comment.destination
    comments = db.relationship('Comment', backref='destination')

    
	
    def __repr__(self): #string print method
        return "<Name: {}>".format(self.name)

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(400))
    created_at = db.Column(db.DateTime, default=datetime.now())
    #add the foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    destination_id = db.Column(db.Integer, db.ForeignKey('destinations.id'))


    def __repr__(self):
        return "<Comment: {}>".format(self.text)

Workshop8/travel/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import TextAreaField,SubmitField, StringField, PasswordField
from wtforms.validators import InputRequired, Length, Email, EqualTo
from flask_wtf.file import FileRequired, FileField, FileAllowed

#add the types of files allowed as a set
ALLOWED_FILE = {'png', 'jpg', 'JPG', 'PNG'}


class DestinationForm(FlaskForm):
  name = StringField('Country', validators=[InputRequired()])
  # adding two validators, one to ensure input is entered and other to check if the 
  #description meets the length requirements
  description = TextAreaField('Description', 
            validators=[InputRequired()])
  #create a filefield that takes two validators - File required and File Allowed
  image = FileField('Destination Image', validators=[FileRequired(message='Image can not be empty'),
                                         FileAllowed(ALLOWED_FILE, message='Only support png, jpg, JPG, PNG, bmp')])
   
  currency = StringField('Currency', validators=[InputRequired()])
  submit = SubmitField("Create")
  #create a filefield that takes two validators - File required and File Allowed
  image = FileField('Destination Image', validators=[
  FileRequired(message='Image can not be empty'),FileAllowed(ALLOWED_FILE, message='Only supports png, jpg, JPG, PNG')])
  #this should already be there in the forms.py
  
class CommentForm(FlaskForm):
  text = TextAreaField('Comment', [InputRequired()])
  submit = SubmitField('Create')

#creates the login information
class LoginForm(FlaskForm):
    user_name=StringField("User Name", validators=[InputRequired('Enter user name')])
    password=PasswordField("Password", validators=[InputRequired('Enter user password')])
    submit = SubmitField("Login")

 # this is the registration form
class RegisterForm(FlaskForm):
    user_name=StringField("User Name", validators=[InputRequired()])
    email_id = StringField("Email Address", validators=[Email("Please enter a valid email")])
    
    #linking two fields - password should be equal to data entered in confirm
    password=PasswordField("Password", validators=[InputRequired(),
                  EqualTo('confirm', message="Passwords should match")])
    confirm = PasswordField("Confirm Password")
    #submit button
    submit = SubmitField("Register")

Workshop8/travel/__init__.py
#import flask - from the package import class
from flask import Flask 
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()

#create a function that creates a web application
# a web server will run this web application
def create_app():
  
    app=Flask(__name__)  # this is the name of the module/package that is calling this app
    app.debug=True
    app.secret_key='utroutoru'
    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///travel123.sqlite'
    #initialize db with flask app
    db.init_app(app)

    bootstrap = Bootstrap(app)
    
    UPLOAD_FOLDER = '/static/image'
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


    #importing views module here to avoid circular references
    # a commonly used practice.
    from . import views
    app.register_blueprint(views.mainbp)

    from . import destinations
    app.register_blueprint(destinations.bp)
    
    return app

Workshop8/travel/auth.py
from flask import Blueprint
from flask import request
from flask import session
from flask import render_template
from .forms import LoginForm, RegisterForm

#Use of blue print to group routes, 
# name - first argument is the blue print name 
# import name - second argument - helps identify the root url for it 
bp = Blueprint('auth', __name__)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    loginForm = LoginForm()
    return render_template('user.html', form=loginForm, heading='Login')

@bp.route('/register', methods=['GET', 'POST'])
def register():
    registrationForm = RegisterForm()
    return render_template('user.html', form=registrationForm, heading='Register')

Workshop8/travel/views.py
from flask import Blueprint
from flask import request
from flask import session
from flask import render_template

#Use of blue print to group routes, 
# name - first argument is the blue print name 
# import name - second argument - helps identify the root url for it 
mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    return render_template("index.html")

Workshop8/travel/templates/base.html
<html>
<head>
 <!-- Title of the app-->
<title>My Travel App</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 </head>
<body>
    <!-- Header -->
    <header class="bg-light border-bottom">

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">

        <!-- Your Travel App Name or Logo -->
        <a href="/" class="navbar-brand">
            My Travel App - Welcome {{ user }}
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar -->
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="#">Destinations</a> 
            <a class="nav-item nav-link" href="#">Bookings</a> 
            </div>
        </div>
        </div>
    </nav>


    {% block header %}
    {% endblock %}

    </header>
    
    {% block content %}
    {% endblock %}

    <footer class="footer">
        <div class="text-center py-2 bg-light">
            <span class="text-dark">Copyright &copy; 2019</span>
        </div>
    </footer> 
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    
    
  </body>
  </html>

Workshop8/travel/templates/destinations/create.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12">

        <h1>Add Travel Destination</h1>
        <p>Enter a country that you will help clients travel to.</p>

        {{wtf.quick_form(form)}}
        
      </div>
    </div>
  </div>

{% endblock %}

Workshop8/travel/templates/destinations/show.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}  
  <div class="container">  
    <div class="row mt-5 mb-3">  
      <div class="col-md-12">  
        <div class="float-left">  
          <h1 class="mb-0">{{destination.name}}</h1>  
          <p>Popular Destination</p>  
        </div>  
 
        <div class="float-right text-right">  
          <p class="mb-0">1 AUD equals</p>  
          <h2 id="exchange-rate">{{destination.currency}}</h1>  
        </div>  
      </div>  
    </div>  
 
    <!-- Destination --> 
    <div class="row">  
      <div class="col-md-12">  
        <div class="card my-3">  
          <div class="card-body">  
            <div class="media">  
              <img class="align-self-start mr-3" src="{{destination.image}}" style="max-width: 250px;">  
              <div class="media-body">  
                <small class="font-weight-bold text-muted">Stay 2 nights</small>  
                <h5 class="mt-0">{{destination.name}}</h5>  
                <p>{{destination.description}}</p>  
                <a href="#" class="btn btn-danger">Book Now</a>  
              </div>  
            </div>  
          </div>  
        </div>  
      </div>  
    </div>     
 
    {{wtf.quick_form(form,
      "/destinations/{0}/comment".format(destination.id))}}
 
    <hr>  
 
    <!-- Comments -->  
    <div class="row">  
      <div class="col-md-12">  
        <h2>Comments</h1>  
      </div>  
    </div>  

    {{wtf.quick_form(form, "/destinations/{0}/comment".format(1))}}

    {% for comment in destination.comments %}
    <div class="row border-bottom">  
      <div class="col-md-12">  
        <b>{{comment.user}}<span class="ml-2 text-muted">{{comment.created_at}}</span></b>  
        <p>{{comment.text}}</p>  
      </div>  
    </div>  
    {% endfor %}
  </div>  
 
  
{% endblock %}  

Workshop8/travel/templates/index.html
{% extends 'base.html' %}

{% block header %}
  <!--Jumbotron-->
  <div class="container">
    <div class="row justify-content-center mt-5 pb-4">
      <div class="col-md-8">
        <div class="jumbotron shadow py-4 mb-5 ">
          <h1 class="text-center">Find our best travel deals</h1>
          <form class="form-inline d-flex flex-nowrap">
            <select class="form-control flex-grow-1 my-1 mr-sm-2" id="inlineFormCustomSelectPref">
              <option selected>Select a destination...</option>
              <option value="america">America</option>
              <option value="africa">Africa</option>
            </select>
            <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
<div class="container">
  <!-- justified in the center, margin top and bottom and the column contains a 10 grid -->
 <div class="row mt-5 mb-5 justify-content-center">
   <div class="col-md-10">
     <div class="media border p-3">
       <img class="align-self-center mr-3" style="max-width: 120px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png" alt="Planet Earth">
       <div class="align-self-center media-body">
         <h5 class="mt-0">Find the best destinations on earth</h5>
         <p class="d-none d-sm-block">Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla.</p>
         <a href="#" class="btn btn-primary">Join Now</a>
       </div>
     </div>
   </div>
 </div>

 <div class="card-deck mb-3">
   <div class="card">
     <img class="card-img-top" src="https://media-cdn.tripadvisor.com/media/photo-s/0e/9c/a0/02/eiffel-tower.jpg" alt="France">
     <div class="card-body">
       <h5 class="card-title">France</h5>
       <p class="card-text">France, in Western Europe, encompasses medieval cities, alpine villages and Mediterranean beaches. Paris, its capital, is famed for its fashion houses, classical art museums including the Louvre and monuments like the Eiffel Tower. The country is also renowned for its wines and sophisticated cuisine. Lascaux’s ancient cave drawings, 
         Lyon’s Roman theater and the vast Palace of Versailles attest to its rich history.</p>
       <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
     </div>
   </div>
   <div class="card">
     <img class="card-img-top" src="https://media-cdn.tripadvisor.com/media/photo-s/12/44/87/23/london.jpg" alt="United Kingdom">
     <div class="card-body">
       <h5 class="card-title">United Kingdom</h5>
       <p class="card-text">The United Kingdom, made up of England, Scotland, Wales and Northern Ireland, is an island nation in northwestern Europe. England – birthplace of Shakespeare and The Beatles – is home to the capital, London, a globally influential centre of finance and culture. England is also site of Neolithic Stonehenge, 
         Bath’s Roman spa and centuries-old universities at Oxford and Cambridge.</p>
       <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
     </div>
   </div>
   <div class="card">
     <img class="card-img-top" src="https://media-cdn.tripadvisor.com/media/photo-s/12/44/6e/a0/rome.jpg" alt="Italy">
     <div class="card-body">
       <h5 class="card-title">Italy</h5>
       <p class="card-text">Epicentre of the Roman Empire and birthplace of the Renaissance, this
         European virtuoso groans under the weight of its cultural cachet: it's here that you'll stand in the
         presence of Michelangelo's David and Sistine Chapel frescoes, Botticelli's Birth of Venus and
         Primavera and da Vinci's The Last Supper.</p>
       <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
     </div>
   </div>
 </div>
</div>
{% endblock %}

Workshop8/travel/templates/login.html
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script></head>
<body>

<div class="container col-md-6">
  <h2>Login Form</h2>
  <!--update the action and the method with relevant information-->
  <form action="", method="POST">
    <!-- keeps the label and text in a group vertically stacked--> 
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
  
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
    </div>

    <button type="submit" class="btn btn-default">Submit</button>
 
  </form>
</body>
</html>

Workshop8/travel/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container-fluid">
    <div class="page-header">
        <h4>{{heading}}</h4>
    </div>

    {% with messages = get_flashed_messages() %}
    {% if messages %} <!-- check if there are any messages -->
    <div class="container-fluid">
        <div class="row mt-3 mb-3">
            <div class="col-md-12">
            {% for message in messages %} <!--loop through the messages-->
                <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
            {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}

    <!-- Form rendering is simple and easy if using bootstrap -->
    <div class="col-md-6 ml-5">
    {{wtf.quick_form(form)}}
    </div>

    <!-- When you have login form, then do show the user a link to register -->
    {% if heading|lower =='login' %}
    <div class="col-md-4 mb-5 ml-5">
        <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
    </div>
    {% endif %}
</div>
{% endblock %}